-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TYPE user_role AS ENUM ('admin', 'user', 'manager');
CREATE TYPE task_priority AS ENUM ('high', 'medium', 'low');
CREATE TYPE task_status AS ENUM ('in_process', 'completed', 'did_not_start');

CREATE TABLE IF NOT EXISTS public."User"
(
    id serial NOT NULL,
    username character varying(40) NOT NULL,
    first_name character varying(40),
    last_name character varying(40),
    email character varying(40),
    phone character varying(40),
    is_active boolean,
    role user_role,
    created_at date,
    PRIMARY KEY (id),
    CONSTRAINT user_uniques UNIQUE (id, username, phone, email)
);

CREATE TABLE IF NOT EXISTS public."Task"
(
    id serial NOT NULL,
    name character varying(20) NOT NULL,
    description text,
    created_at date NOT NULL,
    deadline_date date NOT NULL,
    is_completed boolean NOT NULL,
    display_xcoord integer NOT NULL,
    display_ycoord integer NOT NULL,
	priority task_priority NOT NULL;
	status task_status NOT NULL;
    user_id integer NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT task_uniques UNIQUE (id, name)
);

CREATE INDEX idx_task_userid ON public."Task" (user_id);

ALTER TABLE IF EXISTS public."Task"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;